version: '3'
services:
  portal:
    build:
      context: ./portal
    depends_on:
      - database
    ports:
      - "8000:8000"
      - "8080:8080"
      - "11311:11311"
    volumes:
      - document_library:/opt/liferay/data/document_library

  database:
    image: mariadb:10.4
    container_name: liferay-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=liferay
      - MYSQL_DATABASE=lportal
    volumes:
      - mariadb_data:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"

  smtp:
    image: reachfive/fake-smtp-server
    ports:
        - 1080:1080

  es01:
    image: elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: ["elasticsearch", "-Elogger.level=ERROR"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  es02:
    image: elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: ["elasticsearch", "-Elogger.level=ERROR"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02_data:/usr/share/elasticsearch/data

volumes:
  mariadb_data:
  document_library:
  es01_data:
  es02_data:
